CANVAS_FOLDER: Canvas
GRADESCOPE_FOLDER: Gradescope
OUTPUT_FOLDER: Output
CANVAS_API:
  URL: https://canvas.instructure.com
  NET_ID_ENDPOINT: login_id
  SID_ENDPOINT: sis_user_id
  KEY: example_key




#SEE THE README.txt FILE FOR INFORMATION ON HOW TO SET UP THIS FILE
#DO NOT CHANGE THE URL, NET_ID_ENDPOINT, OR SID_ENDPOINT unless the Canvas API changes
